-- MySQL Script generated by MySQL Workbench
-- Thu Dec  4 14:32:00 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `token` CHAR(36) NOT NULL DEFAULT (UUID()),
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bericht`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bericht` (
  `idbericht` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(250) NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idbericht`),
  INDEX `fk_bericht_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_bericht_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_has_bericht`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_has_bericht` (
  `user_iduser` INT NOT NULL,
  `bericht_idbericht` INT NOT NULL,
  PRIMARY KEY (`user_iduser`, `bericht_idbericht`),
  INDEX `fk_user_has_bericht_bericht1_idx` (`bericht_idbericht` ASC) VISIBLE,
  INDEX `fk_user_has_bericht_user_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_bericht_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_bericht_bericht1`
    FOREIGN KEY (`bericht_idbericht`)
    REFERENCES `bericht` (`idbericht`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
